services:
  - type: web
    name: mathnu-alumni
    plan: free
    runtime: python
    startCommand: python app.py
    envVars:
      - key: ALUMNI_SECRET
        generateValue: true
      - key: HOT_RELOAD
        value: "0"
